php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run -v
# - vendor/bin/phpunit